### ISSUE TITLE
command listDatabases requires authentication

### ISSUE THREAD

**Issue by PierreTurnbull** [mongo-express/mongo-express#720]
I can't connect to mongo anymore, from 1.0.0-alpha. However on 0.54.0 and before it works well.

My docker compose:
```
version: "3"
services:
  mongo:
    image: mongo:4.4.6
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ~/owlab_volumes/mongo:/data/db
  mongo-express:
    image: mongo-express:latest
    ports:
      - 7081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
```

The error:
```
(node:9) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:9) UnhandledPromiseRejectionWarning: MongoError: command listDatabases requires authentication
    at Connection.<anonymous> (/node_modules/mongodb/lib/core/connection/pool.js:451:61)
    at Connection.emit (events.js:314:20)
    at processMessage (/node_modules/mongodb/lib/core/connection/connection.js:451:10)
    at Socket.<anonymous> (/node_modules/mongodb/lib/core/connection/connection.js:620:15)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
(node:9) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by infoShare** [comment]
Same issue here:

After last updates without any changes new issue occurred on mongo express (using docker compose):

Configuration:
```
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: XXX
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: XXX
```

And error:

```
(node:6) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:6) UnhandledPromiseRejectionWarning: MongoError: command listDatabases requires authentication
    at Connection.<anonymous> (/node_modules/mongodb/lib/core/connection/pool.js:451:61)
    at Connection.emit (events.js:314:20)
    at processMessage (/node_modules/mongodb/lib/core/connection/connection.js:451:10)
    at Socket.<anonymous> (/node_modules/mongodb/lib/core/connection/connection.js:620:15)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by khoibv** [comment]
Tried to use old version, it's work.

```
mongo-express:
    image: mongo-express:latest
```

**Comment by guiananias** [comment]
You need to use the env variable: `ME_CONFIG_MONGODB_URL`. In my use case I made this:

```yml
# docker-compose.yml
version: "3.8"

services:
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_URL="mongodb://<user>:<password>@<mongo-container-name>:<container-port>/"
```

With this, I can run Mongo Express correctly.

**Comment by pylandure-cobredia** [comment]
The proposed solution does not allow to make use of docker secrets to store passwords and username. There is no ME_CONFIG_MONGODB_URL_FILE.
This can be a security issue.

**Comment by drivera-armedia** [comment]
Has this issue been fixed? I'm still running into this using latest from Docker Hub (1.0.0-alpha.4). The fix mentioned above (involving ME_CONFIG_MONGODB_URL) worked, but embedding credentials like this is a HUGE security risk.

**Comment by riteshkumar4** [comment]
Please try :
      - ME_CONFIG_MONGODB_ENABLE_ADMIN = false
      - ME_CONFIG_MONGODB_AUTH_USERNAME=XXXX              //Databse Admin Username
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=XXXX             //Databse Admin Password
      - ME_CONFIG_BASICAUTH_USERNAME=XXXX                      //Mongo Express Username or Mongo Docker Username
      - ME_CONFIG_BASICAUTH_PASSWORD=XXXX                      //Mongo Express Password or Mongo Docker Password

**Comment by sin66x** [comment]
> The proposed solution does not allow to make use of docker secrets to store passwords and username. There is no ME_CONFIG_MONGODB_URL_FILE. This can be a security issue.

I do agree with you, It should be fixed but until then I have saved the whole connection string in the secrets

**Comment by raghvmaheshwari** [comment]
is this issue being fixed because I have tried everything but still getting this:
`Welcome to mongo-express
------------------------


(node:7) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:7) UnhandledPromiseRejectionWarning: MongoError: command listDatabases requires authentication
    at Connection.<anonymous> (/node_modules/mongodb/lib/core/connection/pool.js:453:61)
    at Connection.emit (events.js:314:20)
    at processMessage (/node_modules/mongodb/lib/core/connection/connection.js:456:10)
    at Socket.<anonymous> (/node_modules/mongodb/lib/core/connection/connection.js:625:15)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by raghvmaheshwari** [comment]
is this issue being fixed because I have tried everything but still getting this:
```

Welcome to mongo-express
------------------------


(node:7) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:7) UnhandledPromiseRejectionWarning: MongoError: command listDatabases requires authentication
    at Connection.<anonymous> (/node_modules/mongodb/lib/core/connection/pool.js:453:61)
    at Connection.emit (events.js:314:20)
    at processMessage (/node_modules/mongodb/lib/core/connection/connection.js:456:10)
    at Socket.<anonymous> (/node_modules/mongodb/lib/core/connection/connection.js:625:15)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by edemen** [comment]
I am experiencing the same thing. This is not fixed : (

**Comment by arman-mukatov** [comment]
same error

**Comment by rpsirois** [comment]
Same error for me too using secrets only.

**Comment by raulabad98** [comment]
same error

```
  Welcome to mongo-express
------------------------


(node:7) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Could not connect to database using connectionString: mongodb://username:password@mongo:27017/"
(node:7) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [mongo:27017] on first connect [Error: getaddrinfo ENOTFOUND mongo
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  name: 'MongoNetworkError'
}]
    at Pool.<anonymous> (/node_modules/mongodb/lib/core/topologies/server.js:441:11)
    at Pool.emit (events.js:314:20)
    at /node_modules/mongodb/lib/core/connection/pool.js:564:14
    at /node_modules/mongodb/lib/core/connection/pool.js:1000:11
    at /node_modules/mongodb/lib/core/connection/connect.js:32:7
    at callback (/node_modules/mongodb/lib/core/connection/connect.js:300:5)
    at Socket.<anonymous> (/node_modules/mongodb/lib/core/connection/connect.js:330:7)
    at Object.onceWrapper (events.js:421:26)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by huyenlab19437** [comment]
You can try to downgrade your mongodb to 4.2.1 and use mongo-express 0.54. Hope they can fix.

**Comment by ralphv** [comment]
> ME_CONFIG_MONGODB_URL

This looks like a different issue, not finding your mongo do via the hostname "mongo". Is this run in docker?

**Comment by asamoon** [comment]
got same error
and i try to set `ME_CONFIG_MONGODB_URL` like:

```yml
# docker-compose.yml
version: "3.8"

mongo-express:
    image: mongo-express
...
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
```

it's work for me.

**Comment by aditya-kapre-shrewsbury** [comment]
> got same error and i try to set `ME_CONFIG_MONGODB_URL` like:
> 
> ```yaml
> # docker-compose.yml
> version: "3.8"
> 
> mongo-express:
>     image: mongo-express
> ...
>     environment:
>       ME_CONFIG_MONGODB_ADMINUSERNAME: root
>       ME_CONFIG_MONGODB_ADMINPASSWORD: example
>       ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
> ```
> 
> it's work for me.

This works!

**Comment by Luukvdm** [comment]
After reading through the code a bit, I realized you can set the server and port value.
This causes mongo-express to build the connect URL from the given info.

Not sure why none of the devs have recommended this or why the `ME_CONFIG_MONGODB_SERVER` env var is undocumented.
But this allows setting the root password through a secret instead of hard coding it in the connect URL.

Docker example:
```yaml
# docker-compose.yml
version: "3"

mongo-express:
    image: mongo-express
...
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secure
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
```

Kubernetes example:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "mongo-express"
  labels:
    app.kubernetes.io/name: "mongo-express"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "mongo-express"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "mongo-express"
    spec:
      containers:
      - image: mongo-express
        name: "mongo-express"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        env:
        - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
          value: "true"
        - name: ME_CONFIG_MONGODB_SERVER
          value: "mongodb.default.svc.cluster.local"
        - name: ME_CONFIG_MONGODB_PORT
          value: "27017"
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: "root"
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: "mongodb"
              key: mongodb-root-password
```

**Comment by LukasBastianGTM** [comment]
@Luukvdm 
I coud get my k8s container working as shown your example. The issue is that mongo-express does not seem to be paticularly happy about beeing started like that. 

For me I get this Message in the Dashboard:
Turn on admin in config.js to view server stats!

And the container logs show:
Mongo Express server listening at http://0.0.0.0:8081
Server is open to allow connections from anyone (0.0.0.0)
basicAuth credentials are "admin:pass", it is recommended you change this in your config.js!

The fact that anyone can connect should be fine as you cant directly connect to the k8s container anyways, but the rest seems concerning. I dont really understand the impact this might or might not have on the installation, so a explaination would be hugely apreciated.

**Comment by Shireen305** [comment]
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_URL
          valueFrom: 
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url

`
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  database_url: "mongodb://mongodb-service:27017"
  
  `
Still getting same error

**Comment by Luukvdm** [comment]
[This commit ](https://github.com/mongo-express/mongo-express/commit/a0d1946fa818b333494ff704fe2e5454efe0ae6f) broke that config. 

I created a [pull request ](https://github.com/mongo-express/mongo-express/pull/1594) with an updated example for Kubernetes using the documented variables.
